[[redirects]]
  from = "/*"
  to = "https://calm-plum-rattlesnake-shoe.cyclic.app/getUsers/:splat"
 status = 200
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "POST"}
  